### ISSUE TITLE
显示问题---schema配置参考手册查看不方便

### ISSUE THREAD

**Issue by zhoujw8792** [apache/incubator-dubbo-website#37]
schema配置参考手册下的配置列表表格内容没有显示完整，带有左右拖动滚动条查看文档很不方便

**Comment by MLeft** [comment]
for [zh-cn page](http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-service.html), i set 
```css
table td,th {
    font-size: 12px;
}
.documentation-page .content-section .doc-content {
    padding: 20px 0% 0 5%;
}
```
it looks jut ok :-)

![dubbo_service_table](https://user-images.githubusercontent.com/6762483/45142771-eb6cb100-b1eb-11e8-9509-8b1b2e5a411d.png)
